import React, { useEffect, useMemo, useState } from 'react';
import toast from 'react-hot-toast';
import { DataTable } from '../components';
import { inventoryApi, pharmacyApi } from '../api';

const emptySupplier = { name: '', contact_person: '', phone: '', email: '', gst_number: '', payment_terms: '', address: '' };
const emptyItem = { name: '', item_type: 'consumable', category: '', unit: 'pcs', barcode: '', sku: '', reorder_level: 10, location: '' };
const emptyPo = { supplier_id: '', expected_date: '', notes: '', item_name: '', quantity: '', unit_price: '', tax_amount: '', discount_amount: '' };
const emptyReceive = { purchase_order_id: '', supplier_id: '', name: '', item_type: 'consumable', item_id: '', medicine_id: '', batch_number: '', barcode: '', expiry_date: '', quantity: '', cost_price: '', selling_price: '', location: '', notes: '' };
const emptyReturn = { supplier_id: '', batch_id: '', quantity: '', reason: '' };
const emptyBill = { supplier_id: '', purchase_order_id: '', invoice_number: '', invoice_date: '', due_date: '', amount: '', paid_amount: '', notes: '' };
const emptyDispense = { batch_id: '', patient_id: '', doctor_id: '', quantity: '', selling_price: '', notes: '' };

function number(v) { const n = Number(v); return Number.isFinite(n) ? n : 0; }
function money(v) { return `₹${number(v).toLocaleString('en-IN')}`; }

export default function Inventory({ permissions = {} }) {
  const [loading, setLoading] = useState(true);
  const [summary, setSummary] = useState({});
  const [suppliers, setSuppliers] = useState([]);
  const [items, setItems] = useState([]);
  const [batches, setBatches] = useState([]);
  const [purchaseOrders, setPurchaseOrders] = useState([]);
  const [bills, setBills] = useState([]);
  const [receivings, setReceivings] = useState([]);
  const [returns, setReturns] = useState([]);
  const [transactions, setTransactions] = useState([]);
  const [expiryAlerts, setExpiryAlerts] = useState([]);
  const [medicines, setMedicines] = useState([]);
  const [activePanel, setActivePanel] = useState('receive');
  const [supplierForm, setSupplierForm] = useState(emptySupplier);
  const [itemForm, setItemForm] = useState(emptyItem);
  const [poForm, setPoForm] = useState(emptyPo);
  const [receiveForm, setReceiveForm] = useState(emptyReceive);
  const [returnForm, setReturnForm] = useState(emptyReturn);
  const [billForm, setBillForm] = useState(emptyBill);
  const [dispenseForm, setDispenseForm] = useState(emptyDispense);
  const [search, setSearch] = useState('');

  async function load() {
    setLoading(true);
    try {
      const [sum, sup, itm, bat, po, bill, rec, ret, tx, exp, meds] = await Promise.all([
        inventoryApi.summary(), inventoryApi.suppliers(), inventoryApi.items(), inventoryApi.batches(), inventoryApi.purchaseOrders(), inventoryApi.supplierBills(), inventoryApi.stockReceivings({ limit: 25 }), inventoryApi.stockReturns({ limit: 25 }), inventoryApi.transactions({ limit: 50 }), inventoryApi.expiryAlerts({ days: 45 }), pharmacyApi.list().catch(() => ({ data: [] })),
      ]);
      setSummary(sum.data || {}); setSuppliers(sup.data || []); setItems(itm.data || []); setBatches(bat.data || []); setPurchaseOrders(po.data || []); setBills(bill.data || []); setReceivings(rec.data || []); setReturns(ret.data || []); setTransactions(tx.data || []); setExpiryAlerts(exp.data || []); setMedicines(meds.data || []);
    } catch (err) { toast.error(err.response?.data?.message || 'Inventory load failed'); }
    finally { setLoading(false); }
  }
  useEffect(() => { load(); }, []);

  const filteredBatches = useMemo(() => {
    const q = search.toLowerCase();
    return batches.filter((b) => [b.item_name, b.batch_number, b.barcode, b.supplier_name, b.expiry_date].some((x) => String(x || '').toLowerCase().includes(q)));
  }, [batches, search]);

  async function saveSupplier(e) { e.preventDefault(); try { await inventoryApi.createSupplier(supplierForm); toast.success('Supplier saved'); setSupplierForm(emptySupplier); load(); } catch (err) { toast.error(err.response?.data?.message || 'Supplier save failed'); } }
  async function saveItem(e) { e.preventDefault(); try { await inventoryApi.createItem(itemForm); toast.success('Item saved'); setItemForm(emptyItem); load(); } catch (err) { toast.error(err.response?.data?.message || 'Item save failed'); } }
  async function savePo(e) { e.preventDefault(); try { await inventoryApi.createPurchaseOrder({ supplier_id: poForm.supplier_id, expected_date: poForm.expected_date, notes: poForm.notes, items: [{ name: poForm.item_name, quantity: number(poForm.quantity), unit_price: number(poForm.unit_price), tax_amount: number(poForm.tax_amount), discount_amount: number(poForm.discount_amount) }] }); toast.success('Purchase order created'); setPoForm(emptyPo); load(); } catch (err) { toast.error(err.response?.data?.message || 'PO save failed'); } }
  async function receiveStock(e) { e.preventDefault(); try { await inventoryApi.receiveStock({ purchase_order_id: receiveForm.purchase_order_id, supplier_id: receiveForm.supplier_id, notes: receiveForm.notes, items: [{ item_id: receiveForm.item_id, medicine_id: receiveForm.medicine_id, name: receiveForm.name, item_type: receiveForm.item_type, batch_number: receiveForm.batch_number, barcode: receiveForm.barcode, expiry_date: receiveForm.expiry_date, quantity: number(receiveForm.quantity), cost_price: number(receiveForm.cost_price), selling_price: number(receiveForm.selling_price), location: receiveForm.location }] }); toast.success('Stock received'); setReceiveForm(emptyReceive); load(); } catch (err) { toast.error(err.response?.data?.message || 'Stock receiving failed'); } }
  async function returnStock(e) { e.preventDefault(); try { await inventoryApi.returnStock({ supplier_id: returnForm.supplier_id, reason: returnForm.reason, items: [{ batch_id: returnForm.batch_id, quantity: number(returnForm.quantity) }] }); toast.success('Stock returned'); setReturnForm(emptyReturn); load(); } catch (err) { toast.error(err.response?.data?.message || 'Stock return failed'); } }
  async function saveBill(e) { e.preventDefault(); try { await inventoryApi.createSupplierBill({ ...billForm, amount: number(billForm.amount), paid_amount: number(billForm.paid_amount) }); toast.success('Supplier bill saved'); setBillForm(emptyBill); load(); } catch (err) { toast.error(err.response?.data?.message || 'Bill save failed'); } }
  async function dispenseBatch(e) { e.preventDefault(); try { await inventoryApi.batchDispense({ ...dispenseForm, quantity: number(dispenseForm.quantity), selling_price: number(dispenseForm.selling_price) }); toast.success('Batch dispensed'); setDispenseForm(emptyDispense); load(); } catch (err) { toast.error(err.response?.data?.message || 'Batch dispense failed'); } }

  const canManage = permissions.pharmacyStockManage;
  const canCreate = permissions.pharmacyCreate || canManage;

  return (
    <section className="pharmacyPage inventoryPage">
      <div className="appointmentHero pharmacyHero">
        <div><span className="eyebrow">V31 Enterprise Inventory</span><h1>Inventory + Purchase Orders</h1><p>Purchase orders, supplier bills, stock receiving/return, batch-wise dispensing, barcode fields, consumables and expiry alerts.</p></div>
        <button type="button" className="primaryBtn" onClick={load}>{loading ? 'Refreshing...' : 'Refresh'}</button>
      </div>

      <div className="appointmentStatsGrid pharmacyStatsGrid">
        <div className="appointmentStat"><span>Suppliers</span><strong>{summary.suppliers || 0}</strong></div>
        <div className="appointmentStat"><span>Stock Units</span><strong>{summary.stock_units || 0}</strong></div>
        <div className="appointmentStat"><span>Open POs</span><strong>{summary.open_purchase_orders || 0}</strong></div>
        <div className="appointmentStat"><span>Payable</span><strong>{money(summary.payable_amount)}</strong></div>
        <div className="appointmentStat"><span>Expiry Alerts</span><strong>{summary.expiry_alerts || 0}</strong></div>
      </div>

      <div className="pharmacyFilters"><input placeholder="Search batch, barcode, supplier..." value={search} onChange={(e) => setSearch(e.target.value)} /><select value={activePanel} onChange={(e) => setActivePanel(e.target.value)}><option value="receive">Receive Stock</option><option value="po">Purchase Order</option><option value="supplier">Supplier</option><option value="item">Consumable/Item</option><option value="return">Stock Return</option><option value="bill">Supplier Bill</option><option value="dispense">Batch Dispense</option></select></div>

      {canCreate && activePanel === 'supplier' && <form className="card pharmacyForm" onSubmit={saveSupplier}><h3>Supplier Master</h3><div className="appointmentFormGrid pharmacyFormGrid"><input required placeholder="Supplier Name" value={supplierForm.name} onChange={(e) => setSupplierForm({ ...supplierForm, name: e.target.value })} /><input placeholder="Contact Person" value={supplierForm.contact_person} onChange={(e) => setSupplierForm({ ...supplierForm, contact_person: e.target.value })} /><input placeholder="Phone" value={supplierForm.phone} onChange={(e) => setSupplierForm({ ...supplierForm, phone: e.target.value })} /><input placeholder="Email" value={supplierForm.email} onChange={(e) => setSupplierForm({ ...supplierForm, email: e.target.value })} /><input placeholder="GST Number" value={supplierForm.gst_number} onChange={(e) => setSupplierForm({ ...supplierForm, gst_number: e.target.value })} /><input placeholder="Payment Terms" value={supplierForm.payment_terms} onChange={(e) => setSupplierForm({ ...supplierForm, payment_terms: e.target.value })} /><input placeholder="Address" value={supplierForm.address} onChange={(e) => setSupplierForm({ ...supplierForm, address: e.target.value })} /></div><button className="primaryBtn">Save Supplier</button></form>}

      {canCreate && activePanel === 'item' && <form className="card pharmacyForm" onSubmit={saveItem}><h3>Consumables / Inventory Item</h3><div className="appointmentFormGrid pharmacyFormGrid"><input required placeholder="Item Name" value={itemForm.name} onChange={(e) => setItemForm({ ...itemForm, name: e.target.value })} /><select value={itemForm.item_type} onChange={(e) => setItemForm({ ...itemForm, item_type: e.target.value })}><option value="consumable">Consumable</option><option value="medicine">Medicine</option><option value="equipment">Equipment</option><option value="general">General</option></select><input placeholder="Category" value={itemForm.category} onChange={(e) => setItemForm({ ...itemForm, category: e.target.value })} /><input placeholder="Unit" value={itemForm.unit} onChange={(e) => setItemForm({ ...itemForm, unit: e.target.value })} /><input placeholder="Barcode" value={itemForm.barcode} onChange={(e) => setItemForm({ ...itemForm, barcode: e.target.value })} /><input placeholder="SKU" value={itemForm.sku} onChange={(e) => setItemForm({ ...itemForm, sku: e.target.value })} /><input type="number" placeholder="Reorder Level" value={itemForm.reorder_level} onChange={(e) => setItemForm({ ...itemForm, reorder_level: e.target.value })} /><input placeholder="Location" value={itemForm.location} onChange={(e) => setItemForm({ ...itemForm, location: e.target.value })} /></div><button className="primaryBtn">Save Item</button></form>}

      {canCreate && activePanel === 'po' && <form className="card pharmacyForm" onSubmit={savePo}><h3>Purchase Order</h3><div className="appointmentFormGrid pharmacyFormGrid"><select value={poForm.supplier_id} onChange={(e) => setPoForm({ ...poForm, supplier_id: e.target.value })}><option value="">Select Supplier</option>{suppliers.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select><input type="date" value={poForm.expected_date} onChange={(e) => setPoForm({ ...poForm, expected_date: e.target.value })} /><input required placeholder="Item Name" value={poForm.item_name} onChange={(e) => setPoForm({ ...poForm, item_name: e.target.value })} /><input required type="number" placeholder="Qty" value={poForm.quantity} onChange={(e) => setPoForm({ ...poForm, quantity: e.target.value })} /><input type="number" placeholder="Unit Price" value={poForm.unit_price} onChange={(e) => setPoForm({ ...poForm, unit_price: e.target.value })} /><input type="number" placeholder="Tax" value={poForm.tax_amount} onChange={(e) => setPoForm({ ...poForm, tax_amount: e.target.value })} /><input type="number" placeholder="Discount" value={poForm.discount_amount} onChange={(e) => setPoForm({ ...poForm, discount_amount: e.target.value })} /><input placeholder="Notes" value={poForm.notes} onChange={(e) => setPoForm({ ...poForm, notes: e.target.value })} /></div><button className="primaryBtn">Create PO</button></form>}

      {canManage && activePanel === 'receive' && <form className="card pharmacyForm" onSubmit={receiveStock}><h3>Stock Receiving / GRN</h3><div className="appointmentFormGrid pharmacyFormGrid"><select value={receiveForm.purchase_order_id} onChange={(e) => setReceiveForm({ ...receiveForm, purchase_order_id: e.target.value })}><option value="">PO Optional</option>{purchaseOrders.map((p) => <option key={p.id} value={p.id}>{p.po_number} - {p.supplier_name}</option>)}</select><select value={receiveForm.supplier_id} onChange={(e) => setReceiveForm({ ...receiveForm, supplier_id: e.target.value })}><option value="">Supplier Optional</option>{suppliers.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select><select value={receiveForm.item_id} onChange={(e) => setReceiveForm({ ...receiveForm, item_id: e.target.value, medicine_id: '', name: '' })}><option value="">Select Inventory Item</option>{items.map((i) => <option key={i.id} value={i.id}>{i.name}</option>)}</select><select value={receiveForm.medicine_id} onChange={(e) => setReceiveForm({ ...receiveForm, medicine_id: e.target.value, item_id: '', name: '' })}><option value="">Or Select Medicine</option>{medicines.map((m) => <option key={m.id} value={m.id}>{m.name}</option>)}</select><input placeholder="New Item Name" value={receiveForm.name} onChange={(e) => setReceiveForm({ ...receiveForm, name: e.target.value, item_id: '', medicine_id: '' })} /><select value={receiveForm.item_type} onChange={(e) => setReceiveForm({ ...receiveForm, item_type: e.target.value })}><option value="consumable">Consumable</option><option value="medicine">Medicine</option><option value="equipment">Equipment</option></select><input placeholder="Batch No" value={receiveForm.batch_number} onChange={(e) => setReceiveForm({ ...receiveForm, batch_number: e.target.value })} /><input placeholder="Barcode" value={receiveForm.barcode} onChange={(e) => setReceiveForm({ ...receiveForm, barcode: e.target.value })} /><input type="date" value={receiveForm.expiry_date} onChange={(e) => setReceiveForm({ ...receiveForm, expiry_date: e.target.value })} /><input required type="number" placeholder="Received Qty" value={receiveForm.quantity} onChange={(e) => setReceiveForm({ ...receiveForm, quantity: e.target.value })} /><input type="number" placeholder="Cost Price" value={receiveForm.cost_price} onChange={(e) => setReceiveForm({ ...receiveForm, cost_price: e.target.value })} /><input type="number" placeholder="Selling Price" value={receiveForm.selling_price} onChange={(e) => setReceiveForm({ ...receiveForm, selling_price: e.target.value })} /><input placeholder="Store Location" value={receiveForm.location} onChange={(e) => setReceiveForm({ ...receiveForm, location: e.target.value })} /></div><button className="primaryBtn">Receive Stock</button></form>}

      {canManage && activePanel === 'return' && <form className="card pharmacyForm" onSubmit={returnStock}><h3>Stock Return</h3><div className="appointmentFormGrid pharmacyFormGrid"><select value={returnForm.supplier_id} onChange={(e) => setReturnForm({ ...returnForm, supplier_id: e.target.value })}><option value="">Supplier Optional</option>{suppliers.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select><select required value={returnForm.batch_id} onChange={(e) => setReturnForm({ ...returnForm, batch_id: e.target.value })}><option value="">Select Batch</option>{batches.map((b) => <option key={b.id} value={b.id}>{b.item_name} / {b.batch_number} / Qty {b.quantity}</option>)}</select><input required type="number" placeholder="Return Qty" value={returnForm.quantity} onChange={(e) => setReturnForm({ ...returnForm, quantity: e.target.value })} /><input placeholder="Reason" value={returnForm.reason} onChange={(e) => setReturnForm({ ...returnForm, reason: e.target.value })} /></div><button className="primaryBtn">Return Stock</button></form>}

      {canCreate && activePanel === 'bill' && <form className="card pharmacyForm" onSubmit={saveBill}><h3>Supplier Bill</h3><div className="appointmentFormGrid pharmacyFormGrid"><select value={billForm.supplier_id} onChange={(e) => setBillForm({ ...billForm, supplier_id: e.target.value })}><option value="">Select Supplier</option>{suppliers.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select><select value={billForm.purchase_order_id} onChange={(e) => setBillForm({ ...billForm, purchase_order_id: e.target.value })}><option value="">PO Optional</option>{purchaseOrders.map((p) => <option key={p.id} value={p.id}>{p.po_number}</option>)}</select><input placeholder="Invoice No" value={billForm.invoice_number} onChange={(e) => setBillForm({ ...billForm, invoice_number: e.target.value })} /><input type="date" value={billForm.invoice_date} onChange={(e) => setBillForm({ ...billForm, invoice_date: e.target.value })} /><input type="date" value={billForm.due_date} onChange={(e) => setBillForm({ ...billForm, due_date: e.target.value })} /><input required type="number" placeholder="Amount" value={billForm.amount} onChange={(e) => setBillForm({ ...billForm, amount: e.target.value })} /><input type="number" placeholder="Paid Amount" value={billForm.paid_amount} onChange={(e) => setBillForm({ ...billForm, paid_amount: e.target.value })} /><input placeholder="Notes" value={billForm.notes} onChange={(e) => setBillForm({ ...billForm, notes: e.target.value })} /></div><button className="primaryBtn">Save Bill</button></form>}

      {canManage && activePanel === 'dispense' && <form className="card pharmacyForm" onSubmit={dispenseBatch}><h3>Batch-wise Dispensing</h3><div className="appointmentFormGrid pharmacyFormGrid"><select required value={dispenseForm.batch_id} onChange={(e) => setDispenseForm({ ...dispenseForm, batch_id: e.target.value })}><option value="">Select Batch</option>{batches.filter((b) => Number(b.quantity) > 0).map((b) => <option key={b.id} value={b.id}>{b.item_name} / {b.batch_number} / Qty {b.quantity}</option>)}</select><input placeholder="Patient ID" value={dispenseForm.patient_id} onChange={(e) => setDispenseForm({ ...dispenseForm, patient_id: e.target.value })} /><input placeholder="Doctor ID" value={dispenseForm.doctor_id} onChange={(e) => setDispenseForm({ ...dispenseForm, doctor_id: e.target.value })} /><input required type="number" placeholder="Qty" value={dispenseForm.quantity} onChange={(e) => setDispenseForm({ ...dispenseForm, quantity: e.target.value })} /><input type="number" placeholder="Selling Price" value={dispenseForm.selling_price} onChange={(e) => setDispenseForm({ ...dispenseForm, selling_price: e.target.value })} /><input placeholder="Notes" value={dispenseForm.notes} onChange={(e) => setDispenseForm({ ...dispenseForm, notes: e.target.value })} /></div><button className="primaryBtn">Dispense From Batch</button></form>}

      <div className="card pharmacyInventoryCard"><h3>Batch Stock Register</h3><DataTable rows={filteredBatches.map((b) => ({ item_name: b.item_name, batch_number: b.batch_number, barcode: b.barcode, expiry_date: b.expiry_date, quantity: b.quantity, cost_price: b.cost_price, selling_price: b.selling_price, supplier_name: b.supplier_name }))} /></div>
      <div className="pharmacyActionGrid"><div className="card"><h3>Expiry Alerts</h3><DataTable rows={expiryAlerts.map((b) => ({ item_name: b.item_name, batch_number: b.batch_number, expiry_date: b.expiry_date, quantity: b.quantity }))} /></div><div className="card"><h3>Supplier Bills</h3><DataTable rows={bills.map((b) => ({ bill_number: b.bill_number, supplier_name: b.supplier_name, invoice_number: b.invoice_number, amount: b.amount, paid_amount: b.paid_amount, balance_amount: b.balance_amount, status: b.status }))} /></div></div>
      <div className="pharmacyActionGrid"><div className="card"><h3>Purchase Orders</h3><DataTable rows={purchaseOrders.map((p) => ({ po_number: p.po_number, supplier_name: p.supplier_name, order_date: p.order_date, expected_date: p.expected_date, total_amount: p.total_amount, status: p.status }))} /></div><div className="card"><h3>Recent Transactions</h3><DataTable rows={transactions.map((t) => ({ transaction_type: t.transaction_type, item_name: t.item_name, batch_number: t.batch_number, quantity: t.quantity, balance_after: t.balance_after, reference_type: t.reference_type }))} /></div></div>
      <div className="pharmacyActionGrid"><div className="card"><h3>Suppliers</h3><DataTable rows={suppliers.map((s) => ({ name: s.name, contact_person: s.contact_person, phone: s.phone, email: s.email, gst_number: s.gst_number, status: s.status }))} /></div><div className="card"><h3>Receivings / Returns</h3><DataTable rows={[...receivings.map((r) => ({ type: 'Receiving', number: r.receiving_number, supplier_name: r.supplier_name, date: r.received_date, items: r.items?.length || 0 })), ...returns.map((r) => ({ type: 'Return', number: r.return_number, supplier_name: r.supplier_name, date: r.return_date, items: r.items?.length || 0 }))]} /></div></div>
    </section>
  );
}
