import React, { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import { pilotApi } from '../api/pilotApi';

const empty = { hospital_name:'', contact_name:'', contact_email:'', contact_phone:'', deployment_stage:'planning', go_live_target_date:'', assigned_owner:'', scope_modules:['patients','appointments','billing'], success_criteria:['First live OPD flow completed','Billing and reports verified'], notes:'' };
export default function PilotDeploymentCenter(){
  const [summary,setSummary]=useState(null),[rows,setRows]=useState([]),[tasks,setTasks]=useState([]),[selected,setSelected]=useState(null),[form,setForm]=useState(empty),[task,setTask]=useState({pilot_id:'',title:'',category:'training',priority:'medium',owner:'',due_date:''});
  async function load(){ const [s,r,t]=await Promise.all([pilotApi.summary(),pilotApi.list(),pilotApi.tasks()]); setSummary(s.data); setRows(r.data); setTasks(t.data); }
  useEffect(()=>{load().catch(()=>toast.error('Pilot data load failed'))},[]);
  async function submit(e){e.preventDefault(); await pilotApi.create(form); setForm(empty); toast.success('Pilot deployment created'); load();}
  async function stage(id,deployment_stage){await pilotApi.update(id,{deployment_stage}); toast.success('Stage updated'); load();}
  async function addTask(e){e.preventDefault(); await pilotApi.createTask({...task,pilot_id:Number(task.pilot_id)}); setTask({pilot_id:'',title:'',category:'training',priority:'medium',owner:'',due_date:''}); toast.success('Task added'); load();}
  async function doneTask(id){await pilotApi.updateTask(id,{status:'done'}); load();}
  async function readiness(id){const r=await pilotApi.readiness(id); setSelected(r.data);}
  return <div className="page"><div className="page-header"><div><h1>Pilot Deployment Center</h1><p>Manage first hospital pilots, onboarding tasks, training, migration and go-live readiness.</p></div></div>
    {summary&&<div className="stats-grid"><div className="stat-card"><span>Total Pilots</span><strong>{summary.total}</strong></div><div className="stat-card"><span>Planning</span><strong>{summary.planning}</strong></div><div className="stat-card"><span>Active</span><strong>{summary.active}</strong></div><div className="stat-card"><span>Live</span><strong>{summary.live}</strong></div><div className="stat-card"><span>Open Tasks</span><strong>{summary.tasksOpen}</strong></div></div>}
    <div className="grid two"><form className="card form" onSubmit={submit}><h3>Create Pilot</h3><input placeholder="Hospital name" value={form.hospital_name} onChange={e=>setForm({...form,hospital_name:e.target.value})} required/><input placeholder="Contact name" value={form.contact_name} onChange={e=>setForm({...form,contact_name:e.target.value})}/><input placeholder="Contact email" value={form.contact_email} onChange={e=>setForm({...form,contact_email:e.target.value})}/><input placeholder="Phone" value={form.contact_phone} onChange={e=>setForm({...form,contact_phone:e.target.value})}/><input type="date" value={form.go_live_target_date} onChange={e=>setForm({...form,go_live_target_date:e.target.value})}/><input placeholder="Owner" value={form.assigned_owner} onChange={e=>setForm({...form,assigned_owner:e.target.value})}/><textarea placeholder="Notes" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><button>Create Pilot</button></form>
    <form className="card form" onSubmit={addTask}><h3>Add Pilot Task</h3><select value={task.pilot_id} onChange={e=>setTask({...task,pilot_id:e.target.value})} required><option value="">Select pilot</option>{rows.map(x=><option key={x.id} value={x.id}>{x.hospital_name}</option>)}</select><input placeholder="Task title" value={task.title} onChange={e=>setTask({...task,title:e.target.value})} required/><select value={task.category} onChange={e=>setTask({...task,category:e.target.value})}><option>training</option><option>migration</option><option>configuration</option><option>go_live</option><option>support</option></select><input placeholder="Owner" value={task.owner} onChange={e=>setTask({...task,owner:e.target.value})}/><input type="date" value={task.due_date} onChange={e=>setTask({...task,due_date:e.target.value})}/><button>Add Task</button></form></div>
    <div className="card"><h3>Pilot Deployments</h3><table><thead><tr><th>ID</th><th>Hospital</th><th>Stage</th><th>Go-live</th><th>Owner</th><th>Actions</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.id}</td><td>{r.hospital_name}</td><td>{r.deployment_stage}</td><td>{r.go_live_target_date?new Date(r.go_live_target_date).toLocaleDateString():''}</td><td>{r.assigned_owner}</td><td><button onClick={()=>stage(r.id,'active')}>Active</button><button onClick={()=>stage(r.id,'live')}>Live</button><button onClick={()=>readiness(r.id)}>Readiness</button></td></tr>)}</tbody></table></div>
    {selected&&<div className="card"><h3>{selected.pilot.hospital_name} Readiness: {selected.readinessPercent}%</h3><p>Open tasks: {selected.openTasks}</p></div>}
    <div className="card"><h3>Tasks</h3><table><thead><tr><th>Pilot</th><th>Title</th><th>Category</th><th>Status</th><th>Owner</th><th></th></tr></thead><tbody>{tasks.map(t=><tr key={t.id}><td>{t.pilot_id}</td><td>{t.title}</td><td>{t.category}</td><td>{t.status}</td><td>{t.owner}</td><td>{t.status!=='done'&&<button onClick={()=>doneTask(t.id)}>Done</button>}</td></tr>)}</tbody></table></div>
  </div>
}
