const express=require('express'); const {LabTest,RadiologyTest,Patient,Doctor}=require('../models'); const asyncHandler=require('../utils/asyncHandler'); const {verifyToken}=require('../middleware/auth'); const router=express.Router(); router.use(verifyToken);
async function withNames(rows){ const plain=rows.map(r=>r.toJSON?r.toJSON():r); const patients=await Patient.find({id:{$in:[...new Set(plain.map(x=>x.patient_id).filter(Boolean))]}}).lean(); const doctors=await Doctor.find({id:{$in:[...new Set(plain.map(x=>x.doctor_id).filter(Boolean))]}}).lean(); const pm=Object.fromEntries(patients.map(p=>[p.id,p.full_name])); const dm=Object.fromEntries(doctors.map(d=>[d.id,d.full_name])); return plain.map(x=>({...x,patient_name:pm[x.patient_id],doctor_name:dm[x.doctor_id]}));}
router.post('/lab/book-test',asyncHandler(async(req,res)=>{const r=await LabTest.create({...req.body,test_status:'booked'}); res.status(201).json({message:'Lab test booked',labTestId:r.id});}));
router.patch('/lab/sample-collected/:id',asyncHandler(async(req,res)=>{await LabTest.updateOne({id:Number(req.params.id)},{$set:{test_status:'sample_collected'}}); res.json({message:'Sample marked as collected'});}));
router.patch('/lab/upload-report/:id',asyncHandler(async(req,res)=>{await LabTest.updateOne({id:Number(req.params.id)},{$set:{test_status:'completed',report_file:req.body.report_file||null,report_notes:req.body.report_notes||null}}); res.json({message:'Lab report uploaded'});}));
router.get('/lab/tests',asyncHandler(async(req,res)=>res.json(await withNames(await LabTest.find().sort({id:-1})))));
router.post('/radiology/book-scan',asyncHandler(async(req,res)=>{const r=await RadiologyTest.create({...req.body,status:'booked'}); res.status(201).json({message:'Radiology scan booked',scanId:r.id});}));
router.patch('/radiology/upload-report/:id',asyncHandler(async(req,res)=>{await RadiologyTest.updateOne({id:Number(req.params.id)},{$set:{status:'completed',image_file:req.body.image_file||null,report_file:req.body.report_file||null,report_notes:req.body.report_notes||null}}); res.json({message:'Radiology report uploaded'});}));
router.get('/radiology/tests',asyncHandler(async(req,res)=>res.json(await withNames(await RadiologyTest.find().sort({id:-1}))))); module.exports=router;
