import api from './client';

export const saasApi = {
  overview: () => api.get('/saas/overview'),
  exportTenants: () => api.get('/saas/tenants/export.csv', { responseType: 'blob' }),
  updateSubscription: (id, data) => api.patch(`/tenants/${id}/subscription`, data),
  lifecycle: (id, data) => api.patch(`/tenants/${id}/lifecycle`, data),
  billingSummary: () => api.get('/saas/billing/summary'),
  invoices: (params = {}) => api.get('/saas/invoices', { params }),
  generateInvoice: (data) => api.post('/saas/invoices/generate', data),
  updateInvoiceStatus: (id, data) => api.patch(`/saas/invoices/${id}/status`, data),
  recordPayment: (id, data) => api.post(`/saas/invoices/${id}/payments`, data),
  createPaymentLink: (id, data = {}) => api.post(`/saas/invoices/${id}/payment-link`, data),
  paymentIntents: (params = {}) => api.get('/saas/payment-intents', { params }),
  confirmPaymentIntent: (id, data = {}) => api.post(`/saas/payment-intents/${id}/confirm`, data),
  markOverdueInvoices: () => api.post('/saas/invoices/mark-overdue'),
  exportInvoices: () => api.get('/saas/invoices/export.csv', { responseType: 'blob' }),
  businessPlans: () => api.get('/saas/business/plans'),
  createBusinessPlan: (data) => api.post('/saas/business/plans', data),
  updateBusinessPlan: (planId, data) => api.patch(`/saas/business/plans/${planId}`, data),
  licenseStatus: () => api.get('/saas/license/status'),
  onboardHospital: (data) => api.post('/saas/onboarding/hospitals', data),
  onboardingChecklist: () => api.get('/saas/onboarding/checklist'),
  tenantDbOverview: () => api.get('/tenant-databases/overview'),
  provisionTenantDb: (hospitalId, data = {}) => api.post(`/tenant-databases/${hospitalId}/provision`, data),
  backupTenantDb: (hospitalId, data = {}) => api.post(`/tenant-databases/${hospitalId}/backup`, data),
  tenantBackups: (params = {}) => api.get('/tenant-databases/backups', { params }),
  verifyTenantBackup: (id) => api.post(`/tenant-databases/backups/${id}/verify`),
  migrationPreview: (hospitalId) => api.get(`/tenant-databases/${hospitalId}/migration-preview`),
  runTenantMigration: (hospitalId, data = {}) => api.post(`/tenant-databases/${hospitalId}/migrate`, data),
  tenantMigrations: (params = {}) => api.get('/tenant-databases/migrations', { params }),
  restoreDryRun: (backupId) => api.post(`/tenant-databases/backups/${backupId}/restore-dry-run`),
};
